name: Call
on: pull_request
jobs:
  call:
    uses: ./.github/workflows/reusable-workflows.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-request: write
  print:
    needs: [call]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result> ${MESSAGE}"
        env:
          MESSAGE: ${{ needs.call.outputs.message }}
